#!/usr/bin/env python3
"""Bring the production instances up, from the manifest in deploy/instances.yaml.

This is the narrow, manual half of PLAN.md §10's `provision(repo_url, ref)`:
it does not clone a workshop repo or take a ref, it deploys the content already
vendored under `content/`. What it does buy is that five instances stop being
five hand-run setup wizards, five hand-written env files and five hand-edited
nginx vhosts — the shapes that drift between instances and are impossible to
re-do the same way twice.

    python3 tools/provision.py render               # env files + nginx vhosts
    python3 tools/provision.py up miniasm           # start the stack
    python3 tools/provision.py setup miniasm        # wizard + settings
    python3 tools/provision.py runtimes miniasm     # build the dists it pins
    python3 tools/provision.py sync miniasm         # import the content
    python3 tools/provision.py secrets              # what the passwords are

Every subcommand takes instance names, or none to mean all of them, and every
one is safe to run twice: `render` overwrites generated files from the same
inputs, `setup` skips an instance whose wizard has already run, `runtimes`
skips a dist that is already built, and the sync tools were idempotent
already. See docs/DEPLOY.md for the order to run them in.

**Secrets are generated once** into deploy/secrets.yaml (gitignored) and read
back on every later run, so re-rendering never invalidates a session key or
locks anyone out of a database.
"""
import argparse
import json
import os
import re
import secrets as pysecrets
import subprocess
import sys
import time
from pathlib import Path

import requests
import yaml

ROOT = Path(__file__).resolve().parent.parent
# Rebound by --manifest, so a disposable set of instances (a rehearsal, a
# staging host) can be driven by the same tool without editing the real one.
MANIFEST = ROOT / "deploy" / "instances.yaml"
SECRETS = ROOT / "deploy" / "secrets.yaml"
NGINX_DIR = ROOT / "deploy" / "nginx"
SITES_DIR = NGINX_DIR / "sites"      # generated vhosts, gitignored
ENV_DIR = ROOT / "compose" / "prod"
RUNTIMES = ROOT / "plugins" / "workshop" / "runtimes"

PLACEHOLDER_DOMAIN = "CHANGEME.duckdns.org"


def rel(path):
    """Repo-relative for printing, absolute when the path is outside the repo
    (--manifest can point anywhere)."""
    try:
        return path.relative_to(ROOT)
    except ValueError:
        return path


# --------------------------------------------------------------------------
# Manifest and secrets
# --------------------------------------------------------------------------

def load_manifest():
    if not MANIFEST.is_file():
        sys.exit(f"no manifest at {MANIFEST}")
    data = yaml.safe_load(MANIFEST.read_text())
    domain = data.get("domain", "")
    for inst in data["instances"]:
        inst.setdefault("workshop", False)
        inst["host"] = inst.get("host") or f"{inst['name']}.{domain}"
    return data


def load_secrets(manifest, create=True):
    """Read deploy/secrets.yaml, minting anything not in it yet.

    Generated once and never regenerated: rotating a SECRET_KEY logs out a room
    mid-session, and rotating a database password after the data directory is
    initialized just stops CTFd connecting (the value is read only when MariaDB
    first creates its data directory, see docker-compose.yml).
    """
    data = yaml.safe_load(SECRETS.read_text()) if SECRETS.is_file() else {}
    data.setdefault("instances", {})
    before = json.dumps(data, sort_keys=True)

    # One code for every instance: the audience is told one thing, and this
    # deploy is a demonstration rather than five separate cohorts.
    data.setdefault("registration_code", _words())

    for inst in manifest["instances"]:
        got = data["instances"].setdefault(inst["name"], {})
        got.setdefault("secret_key", pysecrets.token_hex(32))
        got.setdefault("db_password", pysecrets.token_hex(16))
        got.setdefault("db_root_password", pysecrets.token_hex(16))
        got.setdefault("admin_password", pysecrets.token_urlsafe(18))
        got.setdefault("admin_token", "ctfd_" + pysecrets.token_hex(32))

    if create and json.dumps(data, sort_keys=True) != before:
        SECRETS.parent.mkdir(parents=True, exist_ok=True)
        SECRETS.write_text(
            "# GENERATED by tools/provision.py, and gitignored. Values are\n"
            "# minted once and reused: rotating them mid-deploy logs everyone\n"
            "# out or breaks the database connection. Back this file up — it\n"
            "# is the only copy of the admin passwords.\n"
            + yaml.safe_dump(data, sort_keys=True))
        SECRETS.chmod(0o600)
        print(f"secrets: wrote {rel(SECRETS)}")
    return data


def _words():
    """A registration code a teenager can retype off a slide without errors."""
    alphabet = "abcdefghijkmnpqrstuvwxyz23456789"   # no l/o/0/1
    return "-".join("".join(pysecrets.choice(alphabet) for _ in range(4))
                    for _ in range(3))


def content_meta(inst):
    """The instance's title and blurb, read from the content it serves.

    Not copied into the manifest: a second copy of a name is a copy that drifts
    away from the one participants actually read.
    """
    path = ROOT / inst["content"]
    if inst["workshop"]:
        doc = yaml.safe_load((path / "workshop.yaml").read_text())["workshop"]
    else:
        doc = yaml.safe_load((path / "subject.yaml").read_text())["project"]
    return doc.get("name", inst["name"]), doc.get("summary", "")


def admin_email(inst):
    """The preset admin's address. It is also what the wizard registers, so the
    two describe one account rather than two (CTFd/utils/security/auth.py:47
    matches on email)."""
    return f"admin@{inst['host']}"


def subject_dirs(inst):
    """Every subject directory this instance serves — one, or a workshop's several."""
    path = ROOT / inst["content"]
    if not inst["workshop"]:
        return [path]
    doc = yaml.safe_load((path / "workshop.yaml").read_text())
    return [(path / s["path"]).resolve() for s in doc["subjects"]]


def select(manifest, names):
    chosen = [i for i in manifest["instances"] if not names or i["name"] in names]
    unknown = set(names) - {i["name"] for i in manifest["instances"]}
    if unknown:
        sys.exit(f"unknown instance(s): {', '.join(sorted(unknown))}")
    return chosen


# --------------------------------------------------------------------------
# render
# --------------------------------------------------------------------------

def cmd_render(manifest, sec, args):
    if manifest.get("domain") == PLACEHOLDER_DOMAIN:
        sys.exit(f"set `domain:` in {rel(MANIFEST)} first — it is "
                 f"still the placeholder, and every vhost would be generated "
                 f"for {PLACEHOLDER_DOMAIN}.")

    ENV_DIR.mkdir(parents=True, exist_ok=True)
    SITES_DIR.mkdir(parents=True, exist_ok=True)
    tmpl = (NGINX_DIR / "vhost.conf.tmpl").read_text()
    tls_tmpl = (NGINX_DIR / "vhost-tls.conf.tmpl").read_text()

    for inst in select(manifest, args.instances):
        s = sec["instances"][inst["name"]]
        env = ENV_DIR / f"{inst['name']}.env"
        env.write_text(f"""\
# GENERATED by tools/provision.py from deploy/instances.yaml. Gitignored.
#
#   docker compose --env-file {rel(env)} -p ctfd-{inst['name']} up -d
#
# Serves {inst['content']} at https://{inst['host']}/
WS_PORT={inst['port']}
WS_DATA=./.data-prod-{inst['name']}
WS_BIND=127.0.0.1
WS_SECRET_KEY={s['secret_key']}
WS_REVERSE_PROXY=true
WS_DB_PASSWORD={s['db_password']}
WS_DB_ROOT_PASSWORD={s['db_root_password']}
WS_ADMIN_NAME=admin
WS_ADMIN_EMAIL={admin_email(inst)}
WS_ADMIN_PASSWORD={s['admin_password']}
WS_ADMIN_TOKEN={s['admin_token']}
""")
        env.chmod(0o600)

        body = tmpl.replace("@@TLS@@", tls_tmpl if args.tls else
                            "# TLS block omitted: no certificate yet. Obtain one,\n"
                            "# then re-run `provision.py render --tls`.")
        for k, v in [("@@NAME@@", inst["name"]), ("@@HOST@@", inst["host"]),
                     ("@@PORT@@", str(inst["port"])), ("@@RUNTIMES@@", str(RUNTIMES))]:
            body = body.replace(k, v)
        (SITES_DIR / f"{inst['host']}.conf").write_text(body)

        print(f"render {inst['name']:15s} -> compose/prod/{inst['name']}.env, "
              f"deploy/nginx/sites/{inst['host']}.conf"
              f"{'' if args.tls else '  (http only)'}")


# --------------------------------------------------------------------------
# up
# --------------------------------------------------------------------------

def compose(inst, *cmd):
    env = ENV_DIR / f"{inst['name']}.env"
    if not env.is_file():
        sys.exit(f"{rel(env)} missing — run `provision.py render` first")
    return subprocess.run(
        ["docker", "compose", "--env-file", str(env), "-p", f"ctfd-{inst['name']}",
         *cmd], cwd=ROOT, check=True)


def cmd_up(manifest, sec, args):
    for inst in select(manifest, args.instances):
        print(f"== up {inst['name']}")
        compose(inst, "up", "-d")


def cmd_down(manifest, sec, args):
    for inst in select(manifest, args.instances):
        print(f"== down {inst['name']}")
        compose(inst, "down")


# --------------------------------------------------------------------------
# setup — the wizard, then the settings the wizard cannot express
# --------------------------------------------------------------------------

def base_url(inst, args):
    # Through the loopback port by default. The vhost is the same application,
    # but going through it makes the setup depend on TLS being finished, and
    # setup has to be able to run before that.
    return args.url or f"http://127.0.0.1:{inst['port']}"


def wait_up(url, timeout=180):
    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            if requests.get(url, timeout=5).status_code < 500:
                return True
        except requests.RequestException:
            pass
        time.sleep(2)
    return False


def nonce(session, url):
    r = session.get(url)
    m = (re.search(r"'csrfNonce':\s*\"([0-9a-f]+)\"", r.text)
         or re.search(r'name="nonce"[^>]*value="([0-9a-f]+)"', r.text))
    if not m:
        raise RuntimeError(f"no CSRF nonce at {url} (status {r.status_code})")
    return m.group(1)


def cmd_setup(manifest, sec, args):
    defaults = manifest.get("defaults", {})
    for inst in select(manifest, args.instances):
        s = sec["instances"][inst["name"]]
        url = base_url(inst, args)
        name, summary = content_meta(inst)
        print(f"== setup {inst['name']} ({url})")

        if not wait_up(url):
            sys.exit(f"  {inst['name']} did not answer at {url}")

        session = requests.Session()
        r = session.get(url + "/setup", allow_redirects=False)
        if r.status_code in (301, 302):
            print("  wizard already run, skipping")
        else:
            # The wizard's admin *is* the preset admin: same email, so
            # `generate_preset_admin` later finds this account rather than
            # creating a second one (CTFd/utils/security/auth.py:38).
            r = session.post(url + "/setup", data={
                "ctf_name": name,
                "ctf_description": summary,
                "user_mode": defaults.get("user_mode", "users"),
                "name": "admin",
                "email": admin_email(inst),
                "password": s["admin_password"],
                "challenge_visibility": "private",
                "account_visibility": "public",
                "score_visibility": "public",
                "registration_visibility": "public",
                "verify_emails": str(defaults.get("verify_emails", False)).lower(),
                "ctf_theme": "core",
                "theme_color": "", "start": "", "end": "",
                "_submit": "Finish",
                "nonce": nonce(session, url + "/setup"),
            }, allow_redirects=False)
            if r.status_code not in (200, 302):
                sys.exit(f"  wizard failed: HTTP {r.status_code}")
            print(f"  wizard done — {name!r}, admin password in deploy/secrets.yaml")

        # Settings the wizard has no field for. The registration code is what
        # keeps an instance on the open internet from filling with strangers,
        # so it matters that this step runs, not just that the wizard did.
        configs = {
            "registration_code": sec["registration_code"],
            "verify_emails": bool(defaults.get("verify_emails", False)),
        }
        if not defaults.get("scoreboard", True):
            configs["score_visibility"] = "hidden"

        r = requests.patch(
            url + "/api/v1/configs", json=configs,
            headers={"Authorization": f"Token {s['admin_token']}",
                     "Content-Type": "application/json"})
        if r.status_code != 200:
            sys.exit(f"  settings failed: HTTP {r.status_code} {r.text[:200]}")
        print(f"  settings applied — registration code {sec['registration_code']!r}")


# --------------------------------------------------------------------------
# runtimes — build exactly the dists the content pins
# --------------------------------------------------------------------------

def pins(inst):
    """{runtime id: commit sha} for every subject this instance serves."""
    out = {}
    for d in subject_dirs(inst):
        rt = (yaml.safe_load((d / "subject.yaml").read_text()) or {}).get("runtime")
        if rt and rt.get("id") and rt.get("version") and not rt.get("external"):
            out[rt["id"]] = rt["version"]
    return out


def cmd_runtimes(manifest, sec, args):
    wanted = {}
    for inst in select(manifest, args.instances):
        wanted.update(pins(inst))
    for runtime_id, version in sorted(wanted.items()):
        dest = RUNTIMES / runtime_id / version
        if dest.is_dir() and not args.force:
            print(f"runtimes {runtime_id}@{version}: already built")
            continue
        print(f"runtimes {runtime_id}@{version}: building")
        subprocess.run([str(ROOT / "tools" / "build_runtime.sh"), runtime_id, version],
                       cwd=ROOT, check=True)
        if not dest.is_dir():
            # build_runtime.sh names the output after the sha it actually
            # checked out. A mismatch means the pin does not resolve to what
            # the subject declares, and the pane would 404 in silence.
            sys.exit(f"  built, but {rel(dest)} does not exist — "
                     f"the pin in subject.yaml does not match the build")


def cmd_prune(manifest, sec, args):
    """Report — or with --delete, remove — dists no subject pins any more.

    Superseded builds accumulate: every re-pin of a runtime leaves the previous
    dist behind, and they are 13-14 MB each. Nothing reads them, but nothing
    collects them either, because the version in the path is exactly what makes
    a dist safe to cache forever.

    Dry by default. A dist that looks unreferenced here is still referenced by
    any *instance* whose `workshop_runtime` config was written by an older sync
    and has not been re-synced since — deleting it turns that pane into a 404.
    """
    keep = set()
    for inst in manifest["instances"]:
        keep |= {(rid, ver) for rid, ver in pins(inst).items()}

    freed = 0
    for runtime_dir in sorted(RUNTIMES.glob("*/")):
        for dist in sorted(runtime_dir.glob("*/")):
            ref = (runtime_dir.name, dist.name)
            size = sum(f.stat().st_size for f in dist.rglob("*") if f.is_file())
            if ref in keep:
                print(f"  keep  {ref[0]}/{ref[1]}  {size / 1e6:.0f} MB  (pinned)")
                continue
            freed += size
            if args.delete:
                subprocess.run(["rm", "-rf", str(dist)], check=True)
                print(f"  DELETED {ref[0]}/{ref[1]}  {size / 1e6:.0f} MB")
            else:
                print(f"  stale {ref[0]}/{ref[1]}  {size / 1e6:.0f} MB")
    if freed and not args.delete:
        print(f"\n{freed / 1e6:.0f} MB unreferenced. Re-run with --delete to remove it,"
              f"\nonce you are sure no instance still serves an older pin.")


# --------------------------------------------------------------------------
# sync — the existing content pipeline, pointed at the instance
# --------------------------------------------------------------------------

def cmd_sync(manifest, sec, args):
    for inst in select(manifest, args.instances):
        s = sec["instances"][inst["name"]]
        url = base_url(inst, args)
        tool = "sync_workshop.py" if inst["workshop"] else "sync_subject.py"
        print(f"== sync {inst['name']} ({tool})")
        cmd = [sys.executable, str(ROOT / "tools" / tool), str(ROOT / inst["content"]),
               "--url", url, "--admin-user", "admin",
               "--admin-pass", s["admin_password"]]
        if not inst["workshop"]:
            # Codes generated for an exercise are only generated once, so this
            # file is what keeps a re-sync from invalidating a code already
            # handed to a room (HANDOFF.md).
            cmd += ["--codes", str(ROOT / f"instructor_codes.{inst['name']}.yaml")]
        subprocess.run(cmd, cwd=ROOT, check=True)


# --------------------------------------------------------------------------
# secrets
# --------------------------------------------------------------------------

def cmd_secrets(manifest, sec, args):
    print(f"registration code (all instances): {sec['registration_code']}\n")
    for inst in select(manifest, args.instances):
        s = sec["instances"][inst["name"]]
        print(f"{inst['name']}  https://{inst['host']}/")
        print(f"  admin password  {s['admin_password']}")
        print(f"  admin API token {s['admin_token']}")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)

    def add(name, fn, **kw):
        p = sub.add_parser(name, **kw)
        p.add_argument("instances", nargs="*", help="instance names (default: all)")
        p.set_defaults(fn=fn)
        return p

    p = add("render", cmd_render, help="write env files and nginx vhosts")
    p.add_argument("--tls", action="store_true",
                   help="include the HTTPS block (only once certbot has issued "
                        "the certificate — nginx will not start without it)")
    add("up", cmd_up, help="docker compose up -d")
    add("down", cmd_down, help="docker compose down")
    p = add("setup", cmd_setup, help="run the CTFd wizard and apply settings")
    p.add_argument("--url", help="override the base URL (default: the loopback port)")
    p = add("runtimes", cmd_runtimes, help="build the runtime dists the content pins")
    p.add_argument("--force", action="store_true", help="rebuild even if present")
    p = add("prune", cmd_prune, help="list runtime dists nothing pins any more")
    p.add_argument("--delete", action="store_true", help="actually remove them")
    p = add("sync", cmd_sync, help="import the content")
    p.add_argument("--url", help="override the base URL (default: the loopback port)")
    add("secrets", cmd_secrets, help="print the generated credentials")

    ap.add_argument("--manifest", help="a manifest other than deploy/instances.yaml; "
                                       "its secrets live beside it as <name>.secrets.yaml")
    args = ap.parse_args()
    if args.manifest:
        global MANIFEST, SECRETS
        MANIFEST = Path(args.manifest).resolve()
        SECRETS = MANIFEST.with_suffix(".secrets.yaml")
    manifest = load_manifest()
    sec = load_secrets(manifest)
    args.fn(manifest, sec, args)


if __name__ == "__main__":
    main()
